Add Toaster API reference
AdobeDocs/uix pull request #2
Opened 2022-11-17 14:02 UTC by skolodyazhnyy

I have added documentation for newly added Toaster API.

## Related Issue

- [DEVX-2599](https://jira.corp.adobe.com/browse/DEVX-2599)

2022-11-17 20:56 UTC, vkublytskyi approved these changes

2022-11-17 20:57 UTC, vkublytskyi commented
Ready to merge after feature delivered to production

2022-11-18 15:50 UTC, kokoc requested changes

2022-11-18 15:50 UTC, kokoc commented on src/pages/services/aem-cf-console-admin/api/index.md
> +| timeout | `number`                                                    |     | An optional timeout in milliseconds when message should automatically disappear. If not set, default timeout value will
For the optional values it would be nice to see default value somewhere

2023-03-09 17:51 UTC, merged