Add "conditional rendering" documentation
AdobeDocs/uix pull request #65
Opened 2023-12-13 21:40 UTC by VladimirZaets

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-12-13 22:03 UTC, nitinja requested changes
I recommend spelling check using google doc or other tool.

2023-12-13 22:03 UTC, nitinja commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +The `defaultButtons` constant contains the buttons that will be rendered every time, doesn't meter what condition is.
typo found **no matter** what

2023-12-13 22:03 UTC, nitinja commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +This technic provide possibility to build complex logic behind the buttons rendering.
spell suggestion: this technic **provides**

2023-12-13 22:42 UTC, vkublytskyi requested changes
Please add description of `fragmentSelections?.getSelections?.()` API

2023-12-13 22:42 UTC, vkublytskyi commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +In React, rendering occurs whenever the state or props of a component change. If the getButtons method is called within the rendering cycle of a component, it will be executed whenever that component
"If the getButtons method is called" - how 3rd party developers know that?
Please rewrite in an assertive way e.g. "getButtons method is called within the rendering cycle of the action bar component."

2023-12-13 22:42 UTC, vkublytskyi commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +You can indeed use this method to dynamically return different sets of buttons based on the data that has changed on the page. For example:
Why explain to 3rd party developers internal implementation?
I think you can have only this statement: "Content Fragment Admin invokes getButtons method each time a user changes content fragments selection. Therefore, you can dynamically return different sets of buttons based on the data that has changed on the page. For example:
Comment
"

2023-12-13 22:42 UTC, vkublytskyi commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +The `defaultButtons` constant contains the buttons that will be rendered every time, doesn't meter what condition is.
Please ask other team members if such a detailed code explanation is needed. I think the code is simple enough to be clear for any developer.

2024-02-06 15:10 UTC, irenelagno requested changes

2024-02-06 15:10 UTC, irenelagno commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +Based on quantity of selected content fragments we rendered different set of buttons.
Based on the quantity of selected content fragments, we render different sets of buttons.

2024-02-06 15:10 UTC, irenelagno commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +This technic provides possibility to build complex logic behind the buttons rendering.
Typo(suggestion to rephrase) : This technique allows for building complex logic behind the button rendering.

2024-02-06 15:10 UTC, irenelagno commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +Content Fragment Admin invokes getButtons method each time a user changes content fragments selection. Therefore, you can dynamically return different sets of buttons based on the data that has chang
Content Fragment Admin invokes the `getButtons` method each time a user changes the content fragments selection. Therefore, you can dynamically return different sets of buttons based on the data that has changed on the page.

2024-02-06 15:10 UTC, irenelagno commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +The `defaultButtons` constant contains the buttons that will be rendered every time, no matter what condition is.
The `defaultButtons` constant contains the buttons that will be rendered every time, regardless of the condition.
On the line `const selections = await guestConnection?.host?.fragmentSelections?.getSelections?.() || [];` 
we get information about the current list of selected content fragments.

2024-02-07 15:13 UTC, irenelagno approved these changes

2024-02-07 15:13 UTC, irenelagno commented on src/pages/services/aem-cf-console-admin/api/action-bar/index.md
> +he defaultButtons constant contains the buttons that will be rendered every time, regardless of the condition.
**The** default..

2024-02-08 15:24 UTC, merged